### ISSUE TITLE
NMS iOS: Autoruns not working as expected

### ISSUE THREAD

**Issue by jbonisteel** [ooni/probe-multiplatform#230]
Note: although I am specifically referencing NMS iOS in this ticket, I assume this same issue would happen with OONI Probe iOS.

This is what I have noticed while testing NMS iOS:

- When I first installed NMS iOS (so totally fresh install on my device) autorun worked as expected **when** the device was plugged in and the 'only while charging' setting was toggled ON. 
- I then toggled OFF the 'only while charging' setting and unplugged my device  
  - Expected results: autoruns should still happen 
  - Actual results: autoruns appeared to stop, no new autoruns happened over multi-hour period
- Then I toggled 'only while charging' back ON and plugged in my device once again-
  - Expected results: autoruns should start up again
  - Actual results: autorun has not started again, even when device is left for long periods (multple hrs). Also worth noting that I deleted and reinstalled the app multiple times and I could still not get autoruns going again, no matter the configuration of settings.  

We had previously discussed that autoruns weren't on the critical path for launching NMS iOS. So we should discuss what that means in terms of the various settings that we have in the app (should we leave them, even though broken, or what). 

Would it at least be possible to have autorun working consistently at least while charging is happening? 

I also assume this same issue would happen on OONI Probe iOS, where autoruns are more critical

**Comment by aanorbel** [comment]
Will look into this. There should be some areas of improvements.

**Comment by jbonisteel** [comment]
>Then I toggled 'only while charging' back ON and plugged in my device once again-
Expected results: autoruns should start up again
Actual results: autorun has not started again, even when device is left for long periods (multple hrs). Also worth noting that I deleted and reinstalled the app multiple times and I could still not get autoruns going again, no matter the configuration of settings.  

I still can't get autorun to re-start as described above. I have tried fully deleting the app and re-installing it as well, and no luck

**Comment by aanorbel** [comment]
Updated the flow on the latest release and should be working as expected.

**Comment by jbonisteel** [comment]
I am still seeing the issue where autoruns do not appear to start again after adjusting the settings. 

I am including some screen recordings. 

In this first recording - you will see the last autorun was 3 hrs ago. Since that last autorun, I disabled the 'only while charging setting' (and phone is unplugged) and no new autoruns have happened for the past three hours. This is consistent with the current issue we see with autoruns. 

https://github.com/user-attachments/assets/10fc93ef-cdd1-4dc6-a3de-1d23940900a8


In the second recording, you will see that I have since re-enabled the 'only while charging' setting (and my phone is plugged in again, you'll have to trust me on that :) ) I have waited an additional two hours and autoruns have not started again. You'll see the timestamp on the last autorun is now 5 hrs ago

https://github.com/user-attachments/assets/4d2b1bc9-6a90-4790-9c17-003f35914c8f

**Comment by sdsantos** [comment]
Closing for now, while we keep monitoring the measurements we have from iOS.
